import type { RuneAvatar } from "./profile-types";

export const RUNE_AVATARS: RuneAvatar[] = [
  {
    id: "ignis",
    name: "Ignis",
    title: "Señor del Fuego",
    element: "FIRE",
    icon: "🔥",
    accentColor: "text-red-400",
    badgeStyle: "bg-red-950/80 text-red-200 border-red-500/60 shadow-[0_0_15px_rgba(239,68,68,0.3)]",
    borderStyle: "border-red-500/50 hover:border-red-400",
    lore: "Invocador forjado en el magma volcánico con espíritu ofensivo inquebrantable.",
  },
  {
    id: "nereida",
    name: "Nereida",
    title: "Oráculo de las Mareas",
    element: "WATER",
    icon: "💧",
    accentColor: "text-cyan-400",
    badgeStyle: "bg-cyan-950/80 text-cyan-200 border-cyan-500/60 shadow-[0_0_15px_rgba(6,182,212,0.3)]",
    borderStyle: "border-cyan-500/50 hover:border-cyan-400",
    lore: "Custodia de barreras fluidas que disipan la fuerza enemiga con calma cósmica.",
  },
  {
    id: "terra",
    name: "Terra",
    title: "Centinela Tectónico",
    element: "EARTH",
    icon: "🌿",
    accentColor: "text-emerald-400",
    badgeStyle: "bg-emerald-950/80 text-emerald-200 border-emerald-500/60 shadow-[0_0_15px_rgba(16,185,129,0.3)]",
    borderStyle: "border-emerald-500/50 hover:border-emerald-400",
    lore: "Guardián de granito cuya paciencia y armadura pétrea resisten mil asedios.",
  },
  {
    id: "zephyr",
    name: "Zephyr",
    title: "Nómada de Tempestades",
    element: "AIR",
    icon: "⚡",
    accentColor: "text-amber-400",
    badgeStyle: "bg-amber-950/80 text-amber-200 border-amber-500/60 shadow-[0_0_15px_rgba(245,158,11,0.3)]",
    borderStyle: "border-amber-500/50 hover:border-amber-400",
    lore: "Ágil cazador que ataca con la velocidad del rayo y esquiva en ráfagas de viento.",
  },
  {
    id: "aether",
    name: "Aether",
    title: "Tejedora Primordial",
    element: "AETHER",
    icon: "🌌",
    accentColor: "text-fuchsia-400",
    badgeStyle: "bg-fuchsia-950/80 text-fuchsia-200 border-fuchsia-500/60 shadow-[0_0_15px_rgba(217,70,239,0.3)]",
    borderStyle: "border-fuchsia-500/50 hover:border-fuchsia-400",
    lore: "Canalizadora de la quintaesencia estelar que fusiona materia y vacío astral.",
  },
  {
    id: "magma",
    name: "Magma",
    title: "Herrero Volcánico",
    element: "MAGMA",
    icon: "🌋",
    accentColor: "text-orange-400",
    badgeStyle: "bg-orange-950/80 text-orange-200 border-orange-500/60 shadow-[0_0_15px_rgba(249,115,22,0.3)]",
    borderStyle: "border-orange-500/50 hover:border-orange-400",
    lore: "Fusión de fuego y roca pura. Domina la presión subterránea de la cordillera.",
  },
  {
    id: "glaciar",
    name: "Glaciar",
    title: "Señor de la Escarcha",
    element: "GLACIER",
    icon: "❄️",
    accentColor: "text-sky-300",
    badgeStyle: "bg-sky-950/80 text-sky-200 border-sky-400/60 shadow-[0_0_15px_rgba(56,189,248,0.3)]",
    borderStyle: "border-sky-400/50 hover:border-sky-300",
    lore: "Hielo perenne que paraliza las voluntades enemigas bajo un frío absoluto.",
  },
  {
    id: "chronos",
    name: "Chronos",
    title: "Arquitecto del Tiempo",
    element: "CHRONOS",
    icon: "🔮",
    accentColor: "text-purple-300",
    badgeStyle: "bg-purple-950/80 text-purple-200 border-purple-500/60 shadow-[0_0_15px_rgba(168,85,247,0.3)]",
    borderStyle: "border-purple-500/50 hover:border-purple-400",
    lore: "Vidente de los ciclos astrales que anticipa cada jugada en el tapete de batalla.",
  },
];

export function getAvatarById(id?: string): RuneAvatar {
  const found = RUNE_AVATARS.find((a) => a.id === id);
  return found || RUNE_AVATARS[0];
}
