/**
 * Catálogo canónico de la Tienda TCG (Bazar Astral).
 * Bounded Context: Shop (Domain Layer)
 */

import type { BoosterPackDefinition, SingleCardListing, CatalystItem } from "./shop-types";

export const BOOSTER_PACKS: BoosterPackDefinition[] = [
  {
    id: "pack-elemental-menor",
    name: "Sobre Elemental Menor",
    subtitle: "Iniciación de Invocador",
    description: "Contiene 3 runas elementales básicas (Fuego, Agua, Tierra o Aire). La fuente ideal de material para el crisol de La Forja.",
    category: "PACKS",
    rarityTier: "BASIC",
    priceXlm: 2.5,
    cardCount: 3,
    guaranteedRarity: "COMMON",
    minTier: "F-",
    maxTier: "D+",
    possibleElements: ["FIRE", "WATER", "EARTH", "AIR"],
    accentColor: "from-blue-600 via-cyan-500 to-teal-400",
    glowColor: "rgba(0, 229, 255, 0.4)",
    icon: "📦",
  },
  {
    id: "pack-arcano-elite",
    name: "Cofre Arcano Élite",
    subtitle: "Esencia de Fusión Garantizada",
    description: "Contiene 4 runas de combate avanzado con al menos 1 criatura Híbrida garantizada (Magma, Vapor, Rayo o Hielo).",
    category: "PACKS",
    rarityTier: "ELITE",
    priceXlm: 6.0,
    cardCount: 4,
    guaranteedRarity: "RARE",
    minTier: "D+",
    maxTier: "B+",
    possibleElements: ["FIRE", "WATER", "EARTH", "AIR", "STEAM", "MAGMA", "LIGHTNING", "ICE", "NATURE"],
    accentColor: "from-purple-600 via-fuchsia-500 to-pink-500",
    glowColor: "rgba(168, 85, 247, 0.5)",
    icon: "💎",
  },
  {
    id: "pack-cosmico-soberano",
    name: "Reliquia Cósmica Soberana",
    subtitle: "Poder Primigenio de las Estrellas",
    description: "El tesoro supremo de la constelación. 5 cartas superiores con alta probabilidad de Rango S, elementos Cósmicos (Aether, Plasma, Celestial) y cartas Foil holográficas.",
    category: "PACKS",
    rarityTier: "COSMIC",
    priceXlm: 15.0,
    cardCount: 5,
    guaranteedRarity: "EPIC",
    minTier: "B+",
    maxTier: "S+",
    possibleElements: [
      "AETHER",
      "CELESTIAL",
      "VOID",
      "COSMOS",
      "PLASMA",
      "MAGMA",
      "LIGHTNING",
      "TEMPEST",
      "TSUNAMI",
    ],
    accentColor: "from-amber-400 via-yellow-300 to-amber-600",
    glowColor: "rgba(245, 158, 11, 0.6)",
    icon: "🔮",
  },
];

export const DAILY_SINGLES: SingleCardListing[] = [
  {
    id: "single-vapor-primordial",
    category: "SINGLES",
    priceXlm: 18.0,
    originalPriceXlm: 24.0,
    discountBadge: "-25% OFERTA",
    stock: 5,
    featured: true,
    card: {
      id: "shop-single-vapor-s",
      name: "Vapor Primordial Ancestral",
      element: "STEAM",
      rarity: "EPIC",
      tier: "S",
      atk: 14,
      def: 12,
      speed: 15,
      power_score: 94,
      image_url: "/cards/primordial-vapor.png",
      lore: "Condensación etérea surgida en el choque primordial de océanos estelares y cometas ígneos.",
      description: "Híbrido de vapor supremo. Desorienta al rival y penetra defensas con alta velocidad.",
      passive_skill: "Velo Térmico: Reduce un 25% el daño entrante en el primer turno.",
    },
  },
  {
    id: "single-ignis-archon",
    category: "SINGLES",
    priceXlm: 12.0,
    stock: 8,
    featured: false,
    card: {
      id: "shop-single-ignis-archon",
      name: "Archon de Magma Fundido",
      element: "MAGMA",
      rarity: "RARE",
      tier: "A",
      atk: 15,
      def: 8,
      speed: 9,
      power_score: 86,
      image_url: "/cards/ignis-sprite.png",
      lore: "Guardián de los volcanes subacuáticos del núcleo de Aether.",
      description: "Furia concentrada de fuego y tierra. Su impacto causa daño residual persistente.",
      passive_skill: "Cenizas Ardientes: +2 de daño adicional por ataque.",
    },
  },
  {
    id: "single-glaciar-coloso",
    category: "SINGLES",
    priceXlm: 10.0,
    stock: 12,
    featured: false,
    card: {
      id: "shop-single-glaciar",
      name: "Coloso de Hielo Absoluto",
      element: "ICE",
      rarity: "RARE",
      tier: "A-",
      atk: 7,
      def: 16,
      speed: 6,
      power_score: 82,
      image_url: "/cards/aqua-nymph.png",
      lore: "Monolito de permafrost milenario esculpido por ventiscas eternas.",
      description: "Muralla defensiva infranqueable. Absorbe los impactos más devastadores.",
      passive_skill: "Armadura Criogénica: Concede +6 de escudo al colocarse en defensa.",
    },
  },
  {
    id: "single-titan-galvanico",
    category: "SINGLES",
    priceXlm: 8.5,
    originalPriceXlm: 11.0,
    discountBadge: "POPULAR",
    stock: 10,
    featured: false,
    card: {
      id: "shop-single-titan-galvanico",
      name: "Titán Galvánico de Rayo",
      element: "LIGHTNING",
      rarity: "UNCOMMON",
      tier: "B+",
      atk: 13,
      def: 7,
      speed: 13,
      power_score: 79,
      image_url: "/cards/lightning.svg",
      lore: "Condensador bio-eléctrico de nubes de tormenta estelar.",
      description: "Ataques relampagueantes que sobrepasan defensas aéreas y de agua.",
      passive_skill: "Descarga Estática: 20% de probabilidad de asestar golpe crítico.",
    },
  },
];

export const CATALYST_ITEMS: CatalystItem[] = [
  {
    id: "catalyst-piedra-aether",
    name: "Piedra Filosofal de Aether",
    subtitle: "Potenciador de Forja Alquímica",
    description: "Reactivo místico que se consume en La Forja. Aumenta un +20% la probabilidad de obtener un rango superior (Tier Step-up) en la síntesis.",
    category: "CATALYSTS",
    priceXlm: 3.5,
    icon: "🔮",
    effect: "+20% Probabilidad de Ascenso de Rango en la Forja",
    accentColor: "border-purple-500/40 bg-purple-950/30 text-purple-300",
  },
  {
    id: "catalyst-filtro-cosmico",
    name: "Filtro de Fusión Cósmica",
    subtitle: "Estabilizador de Núcleo",
    description: "Cristal catalizador que sintoniza las frecuencias arcanas para garantizar que la carta sintetizada adquiera una habilidad pasiva especial.",
    category: "CATALYSTS",
    priceXlm: 5.0,
    icon: "✨",
    effect: "Garantiza Habilidad Pasiva en la siguiente síntesis",
    accentColor: "border-amber-500/40 bg-amber-950/30 text-amber-300",
  },
];
